name: Publish to NPM

on:
  push:
    branches: [ main, master ]
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        registry-url: 'https://registry.npmjs.org'
    
    - name: Install dependencies
      working-directory: plugins/opensearch-ai-backend
      run: npm install
    
    - name: TypeScript type check
      working-directory: plugins/opensearch-ai-backend
      run: npm run tsc:check || echo "Type check warnings - continuing build"
    
    - name: Build package
      working-directory: plugins/opensearch-ai-backend
      run: npm run build
    
    - name: Run tests
      working-directory: plugins/opensearch-ai-backend
      run: npm test
    
    - name: Run lint
      working-directory: plugins/opensearch-ai-backend
      run: npm run lint
    
    - name: Smart version increment
      working-directory: plugins/opensearch-ai-backend
      run: |
        if [[ "${{ github.event_name }}" == "push" ]]; then
          # Get package name and current local version
          PACKAGE_NAME=$(npm pkg get name | tr -d '"')
          LOCAL_VERSION=$(npm pkg get version | tr -d '"')
          
          # Get latest published version from NPM (handle case when package doesn't exist)
          PUBLISHED_VERSION=$(npm view "$PACKAGE_NAME" version 2>/dev/null || echo "0.0.0")
          
          echo "Package: $PACKAGE_NAME"
          echo "Local version: $LOCAL_VERSION"
          echo "Published version: $PUBLISHED_VERSION"
          
          # Function to compare versions and increment
          increment_version() {
            local version=$1
            local major minor patch
            IFS='.' read -r major minor patch <<< "$version"
            patch=$((patch + 1))
            echo "$major.$minor.$patch"
          }
          
          # Determine next version to publish
          if [ "$PUBLISHED_VERSION" = "0.0.0" ]; then
            # Package doesn't exist, use local version
            NEW_VERSION="$LOCAL_VERSION"
          else
            # Compare versions and increment the higher one
            if [ "$LOCAL_VERSION" = "$PUBLISHED_VERSION" ]; then
              # Same version, increment patch
              NEW_VERSION=$(increment_version "$PUBLISHED_VERSION")
            elif dpkg --compare-versions "$LOCAL_VERSION" gt "$PUBLISHED_VERSION"; then
              # Local is higher, use local
              NEW_VERSION="$LOCAL_VERSION"
            else
              # Published is higher, increment published
              NEW_VERSION=$(increment_version "$PUBLISHED_VERSION")
            fi
          fi
          
          # Update package.json with new version
          npm version "$NEW_VERSION" --no-git-tag-version
          echo "Updated version to: $NEW_VERSION"
        fi
    
    - name: Show package info before publish
      working-directory: plugins/opensearch-ai-backend
      run: |
        echo "Package name: $(npm pkg get name)"
        echo "Package version: $(npm pkg get version)"
        echo "NPM registry: $(npm config get registry)"
    
    - name: Publish to NPM
      working-directory: plugins/opensearch-ai-backend
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}